version: '3'
services:
  webui:
    image: adminer
    container_name: webui
    restart: always
    ports:
      - 8080:8080
    networks:
      - skynet
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobarber
    networks:
      - skynet
networks:
  skynet:
    driver: bridge
