version: '3'
services:
  webui:
    image: dockette/adminer:full
    container_name: webui
    restart: always
    ports:
      - 8000:80
    networks:
      - skynet
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobarber
    networks:
      - skynet
  mongo:
    image: mongo
    container_name: mongobarber
    restart: always
    ports:
      - 27017:27017
    networks:
      - skynet
networks:
  skynet:
    driver: bridge
